--------------------------------------------------------
--  파일이 생성됨 - 금요일-12월-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_BOARD_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMMENT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_COMMENT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."BOARD" 
   (	"NUM" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"ID" VARCHAR2(10 BYTE), 
	"POSTDATE" DATE DEFAULT sysdate, 
	"VISITCOUNT" NUMBER(6,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FREEBOARD
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."FREEBOARD" 
   (	"IDX" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"ID" VARCHAR2(10 BYTE), 
	"VISITCOUNT" NUMBER(6,0), 
	"POSTDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FREE_COMMENT
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."FREE_COMMENT" 
   (	"ID" VARCHAR2(30 BYTE), 
	"BOARD_IDX" NUMBER, 
	"PARENT_ID" VARCHAR2(30 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"POSTDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WEBMEMBER
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."WEBMEMBER" 
   (	"ID" VARCHAR2(10 BYTE), 
	"PASS" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WEB_MVCBOARD
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."WEB_MVCBOARD" 
   (	"IDX" NUMBER, 
	"ID" VARCHAR2(30 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"POSTDATE" DATE DEFAULT sysdate, 
	"OFILE" VARCHAR2(200 BYTE), 
	"SFILE" VARCHAR2(30 BYTE), 
	"DOWNCOUNT" NUMBER(5,0) DEFAULT 0, 
	"VISITCOUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into WEBPROJECT_DB.BOARD
SET DEFINE OFF;
REM INSERTING into WEBPROJECT_DB.FREEBOARD
SET DEFINE OFF;
Insert into WEBPROJECT_DB.FREEBOARD (IDX,TITLE,CONTENT,ID,VISITCOUNT,POSTDATE) values (6,'반갑습니다','반갑습니다~','test1',null,to_date('25/12/12','RR/MM/DD'));
Insert into WEBPROJECT_DB.FREEBOARD (IDX,TITLE,CONTENT,ID,VISITCOUNT,POSTDATE) values (1,'111','111','test1',null,to_date('25/12/11','RR/MM/DD'));
Insert into WEBPROJECT_DB.FREEBOARD (IDX,TITLE,CONTENT,ID,VISITCOUNT,POSTDATE) values (2,'222','2222','test1',null,to_date('25/12/11','RR/MM/DD'));
Insert into WEBPROJECT_DB.FREEBOARD (IDX,TITLE,CONTENT,ID,VISITCOUNT,POSTDATE) values (3,'333','333','test1',null,to_date('25/12/11','RR/MM/DD'));
Insert into WEBPROJECT_DB.FREEBOARD (IDX,TITLE,CONTENT,ID,VISITCOUNT,POSTDATE) values (4,'test4','test1','test1',null,to_date('25/12/11','RR/MM/DD'));
Insert into WEBPROJECT_DB.FREEBOARD (IDX,TITLE,CONTENT,ID,VISITCOUNT,POSTDATE) values (5,'안녕하세요','글씨를 한번 길게 써보겠습니다.
글씨를 한번 길게 써보겠습니다.
글씨를 한번 길게 써보겠습니다.
글씨를 한번 길게 써보겠습니다.
글씨를 한번 길게 써보겠습니다.
글씨를 한번 길게 써보겠습니다.글씨를 한번 길게 써보겠습니다.글씨를 한번 길게 써보겠습니다.','test1',null,to_date('25/12/11','RR/MM/DD'));
REM INSERTING into WEBPROJECT_DB.FREE_COMMENT
SET DEFINE OFF;
REM INSERTING into WEBPROJECT_DB.WEBMEMBER
SET DEFINE OFF;
Insert into WEBPROJECT_DB.WEBMEMBER (ID,PASS,NAME,EMAIL) values ('test1','1234','test2','test@naver.com');
Insert into WEBPROJECT_DB.WEBMEMBER (ID,PASS,NAME,EMAIL) values ('test2','1111','test2','test@naver.com');
Insert into WEBPROJECT_DB.WEBMEMBER (ID,PASS,NAME,EMAIL) values ('test3','1111','test3','test@naver.com');
Insert into WEBPROJECT_DB.WEBMEMBER (ID,PASS,NAME,EMAIL) values ('test4','1111','test4','test@naver.com');
Insert into WEBPROJECT_DB.WEBMEMBER (ID,PASS,NAME,EMAIL) values ('test6','1111','test1','test@naver.com');
Insert into WEBPROJECT_DB.WEBMEMBER (ID,PASS,NAME,EMAIL) values ('test7','1111','test1','test@naver.com');
Insert into WEBPROJECT_DB.WEBMEMBER (ID,PASS,NAME,EMAIL) values ('test8','1111','test1','test@naver.com');
Insert into WEBPROJECT_DB.WEBMEMBER (ID,PASS,NAME,EMAIL) values ('test9','1111','test1','test@naver.com');
REM INSERTING into WEBPROJECT_DB.WEB_MVCBOARD
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008443
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008443" ON "WEBPROJECT_DB"."BOARD" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008455
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008455" ON "WEBPROJECT_DB"."WEBMEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008463
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008463" ON "WEBPROJECT_DB"."WEB_MVCBOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008469
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008469" ON "WEBPROJECT_DB"."FREEBOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008472
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008472" ON "WEBPROJECT_DB"."FREE_COMMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008443
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008443" ON "WEBPROJECT_DB"."BOARD" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008469
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008469" ON "WEBPROJECT_DB"."FREEBOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008472
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008472" ON "WEBPROJECT_DB"."FREE_COMMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008455
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008455" ON "WEBPROJECT_DB"."WEBMEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008463
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008463" ON "WEBPROJECT_DB"."WEB_MVCBOARD" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FREEBOARD
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."FREEBOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FREEBOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FREEBOARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FREEBOARD" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FREEBOARD" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FREE_COMMENT
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."FREE_COMMENT" MODIFY ("BOARD_IDX" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FREE_COMMENT" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FREE_COMMENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WEBMEMBER
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."WEBMEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."WEBMEMBER" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."WEBMEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."WEBMEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."WEBMEMBER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WEB_MVCBOARD
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."WEB_MVCBOARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."WEB_MVCBOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."WEB_MVCBOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."WEB_MVCBOARD" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."WEB_MVCBOARD" MODIFY ("DOWNCOUNT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."WEB_MVCBOARD" MODIFY ("VISITCOUNT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."WEB_MVCBOARD" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WEB_MVCBOARD
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."WEB_MVCBOARD" ADD CONSTRAINT "BOARD_MEM_FK2" FOREIGN KEY ("ID")
	  REFERENCES "WEBPROJECT_DB"."WEBMEMBER" ("ID") ENABLE;
